export const UPDATE_SELECTED_FROM_CHAIN = "UPDATE_SELECTED_FROM_CHAIN";
export const UPDATE_SELECTED_TO_CHAIN = "UPDATE_SELECTED_TO_CHAIN";
export const UPDATE_SWITCH_NETWORK_TEXT = "UPDATE_SWITCH_NETWORK_TEXT";
export const TOGGLE_SWITCH_NETWORK_DISPALY = "TOGGLE_SWITCH_NETWORK_DISPALY";