export const UPDATE_TRANSFER_STATE = "UPDATE_TRANSFER_STATE";
export const UPDATE_TRANSFER_STATUS = "UPDATE_TRANSFER_STATUS";
export const UPDATE_CURRENT_STATE = "UPDATE_CURRENT_STATE";
export const UPDATE_TRANSFER_STEPS_LABEL_ARRAY = "UPDATE_TRANSFER_STEPS_LABEL_ARRAY";
export const UPDATE_TRANSFER_STEPS_CONTENT_ARRAY = "UPDATE_TRANSFER_STEPS_CONTENT_ARRAY";