export const UPDATE_TRANSACTION_FEE = "UPDATE_TRANSACTION_FEE"
export const UPDATE_APPROVE_BUTTON_STATE = "UPDATE_APPROVE_BUTTON_STATE"
export const UPDATE_TRANSFER_BUTTON_STATE = "UPDATE_TRANSFER_BUTTON_STATE"
export const UPDATE_ESTIMATED_AMOUNT_TO_GET = "UPDATE_ESTIMATED_AMOUNT_TO_GET"