export const UPDATE_SUPPORTED_TOKENS = "GET_SUPPORTED_TOKENS"
export const SET_SELECTED_TOKEN = "SET_SELECTED_TOKEN"
export const SET_TOKEN_AMOUNT = "SET_TOKEN_AMOUNT"
export const SET_SELECTED_TOKEN_BALANCE = "SET_SELECTED_TOKEN_BALANCE"
export const SET_MIN_DEPOSIT = "SET_MIN_DEPOSIT";
export const SET_MAX_DEPOSIT = "SET_MAX_DEPOSIT";